### PR TITLE
ENH: Add annotation converter script

### PR DESCRIPTION
**Pull request by jcfr**
Example of usage:

```
C:/Python38-x64/python.exe ^
  C:/P/cell-locator/Scripts/CellLocatorAnnotationFormatConverter.py ^
    --from 20190126 ^
    --to 20200918 ^
    --input C:/Users/jchris.fillionr/Desktop/annotation-20190126.json ^
    --output C:/Users/jchris.fillionr/Desktop/annotation-20200918.json
```

See #158

### CODE REVIEW

**Comment by ejarmand** [comment]
I've just tested the conversion script, there seem to be issues converting from 20290126 to 20200918. It seems  like there may be a scaling factor difference between the annotations? 

See the updated annotation here: 
image

compared to the original annotation:

image

**Comment by jcfr** [comment]
Thanks for trying.

Could you include in different comments few example of old style annotation ?

**Comment by ejarmand** [comment]
Yeah,

 sure thing:

[example_jsons.zip](https://github.com/BICCN/cell-locator/files/5315901/example_jsons.zip)

here I have the old annotation style along with the new translation

**Comment by ejarmand** [comment]
Another relevant comparsion:

your 20290126 example annotation file for comparing formats (using release 2020/04/30)

image

vs your 20200918 example annotation file for comparing formats (using your most recent release)

image

vs the 20290126 example annotation converted using this script to 20200918  format 

image

**Comment by jcfr** [comment]
Thanks @ejarmand , having a look at this now

**Comment by jcfr** [comment]
@allemangD  Ideally, we would like to consolidate this with work done in https://github.com/AllenInstitute/cell_locator_tools/tree/main/ConvertBetweenJsonVersions

**Comment by jcfr** [comment]
@allemangD This PR includes the latest changes I worked on. Would appreciate your help to:
* rebase against current master
* confirm that the fixes address issue discussed in https://github.com/BICCN/cell-locator/pull/160#issuecomment-702512235
* update relevant documentation to integrate with readthedocs. Images should be moved to Docs-resource release similar to https://github.com/Slicer/Slicer/releases/tag/docs-resources
* add tests (using pytest)
* think about approach to consolidate with https://github.com/AllenInstitute/cell_locator_tools/tree/main/ConvertBetweenJsonVersions

**Comment by jcfr** [comment]
[annotation_previous_versions.zip](https://github.com/BICCN/cell-locator/files/6632730/annotation_previous_versions.zip)

**Comment by jcfr** [comment]
Closing. Superseded  by https://github.com/BICCN/cell-locator/pull/181

**Pull request closed without merging**
